#!/bin/bash
# 金明健康看板 - 部署命令清单
# 使用方法：复制每个命令块到终端执行

echo "🚀 金明健康看板 - 部署命令清单"
echo "========================================"
echo ""
echo "📋 使用说明："
echo "1. 第1步：先在GitHub网站创建仓库（已在浏览器中打开）"
echo "2. 第2步：复制下面的命令到终端执行"
echo "3. 替换 YOUR_USERNAME 为您的GitHub用户名"
echo ""
echo "========================================"
echo ""

# 第2步：推送代码到GitHub
echo "📤 第2步：推送代码到GitHub"
echo "----------------------------------------"
echo "cd /Users/williamjoy/Desktop/AI/QuantTrading/QuantTrading/Personal/Health"
echo ""
echo "# 添加远程仓库（替换YOUR_USERNAME为您的GitHub用户名）"
echo "git remote add origin https://github.com/YOUR_USERNAME/jinming-health-dashboard.git"
echo ""
echo "# 推送代码到GitHub"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "========================================"
echo ""

# 第3步：访问Netlify
echo "🌐 第3步：连接Netlify"
echo "----------------------------------------"
echo "1. 访问：https://app.netlify.com/start"
echo "2. 选择 'Deploy from Git repository'"
echo "3. 选择 'GitHub' 并授权登录"
echo "4. 选择 'jinming-health-dashboard' 仓库"
echo "5. 构建设置保持默认（留空）"
echo "6. 点击 'Deploy Site'"
echo "7. 等待1-2分钟，网站自动发布"
echo ""
echo "========================================"
echo ""

# 第4步：设置域名
echo "🎨 第4步：设置自定义域名"
echo "----------------------------------------"
echo "1. 在Netlify后台点击 'Site settings'"
echo "2. 点击 'Change site name'"
echo "3. 输入：williamjoy-health"
echo "4. 新域名：https://williamjoy-health.netlify.app"
echo ""
echo "========================================"
echo ""

# 第5步：配置GitHub Secrets
echo "🔑 第5步：配置GitHub Secrets"
echo "----------------------------------------"
echo "1. 访问：https://cloud.ouraring.com/personal-access-tokens"
echo "2. 创建新Token并复制"
echo "3. 打开GitHub仓库 → Settings → Secrets and variables → Actions"
echo "4. 点击 'New repository secret'"
echo "5. Name: OURA_ACCESS_TOKEN"
echo "6. Secret: 粘贴您的Oura Token"
echo "7. 点击 'Add secret'"
echo ""
echo "========================================"
echo ""

# 测试自动更新
echo "⏰ 测试自动更新（可选）"
echo "----------------------------------------"
echo "1. 打开GitHub仓库的Actions页面"
echo "2. 选择 '每日健康看板自动更新' workflow"
echo "3. 点击 'Run workflow' 按钮"
echo "4. 选择分支：main"
echo "5. 点击 'Run workflow' 绿色按钮"
echo ""
echo "========================================"
echo ""

# 验证部署
echo "✅ 验证部署"
echo "----------------------------------------"
echo "1. 访问：https://williamjoy-health.netlify.app"
echo "2. 检查所有Section是否显示"
echo "3. 检查8个图表是否加载"
echo "4. 测试训练日志输入功能"
echo "5. 测试PB更新功能"
echo ""
echo "========================================"
echo ""

echo "🎉 部署完成！"
echo ""
echo "📊 您的网站地址："
echo "https://williamjoy-health.netlify.app"
echo ""
echo "⏰ 自动更新时间："
echo "每天11:00（北京时间）"
echo ""
echo "💰 总成本：\$0/年 ✅"
